export const ROLE_ROLE_ADMIN = "ROLE_ROLE_ADMIN";
export const ROLE_STORE_ADMIN = "ROLE_STORE_ADMIN";
export const ROLE_SYSTEM_ADMIN = "ROLE_SYSTEM_ADMIN";
export const ROLE_PRODUCT_ADMIN = "ROLE_PRODUCT_ADMIN";
export const ROLE_POS_ADMIN = "ROLE_POS_ADMIN";